add_newline = false
format = '$all$directory$character'

[character]
success_symbol = '[❯](boldbluen)'

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'white'

[directory]
# style = "blue"
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = ' $branch'
style = 'green'

[git_status]
format = '([\[$conflicted$stashed$deleted$renamed$modified$typechanged$staged$untracked\]]($style) )'
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "•"
style = "white"
format="[$symbol]($style)"
shell = ["sh"]
